### PR TITLE
Update Background.py

### PR DESCRIPTION
**Pull request by 97-42**

### CODE REVIEW

**Comment by MEGA-Dawg68** [comment]
Can you a description?

**Comment by MEGA-Dawg68** [comment]
It is set to the screen resolution, we need higher than that. Also edit the code already there, no an entire new file

**Comment by MEGA-Dawg68** [comment]
It is set to the screen resolution, we need higher than that. Also edit the code already there, not an entire new file

**Comment by 97-42** [comment]
> It is set to the screen resolution, we need higher than that. Also edit the code already there, not an entire new file

nuh uh

**Pull request closed without merging**
